# Generated by Django 5.1.7 on 2025-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name1', models.CharField(max_length=100)),
                ('last_name2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('modules', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name1', models.CharField(max_length=100)),
                ('last_name2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('courses', models.TextField()),
                ('tutor', models.BooleanField(default=False)),
            ],
        ),
    ]
